name: CI

on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    paths-ignore:
      - README.md

env:
  BUNDLE_WITHOUT: "development"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby-2.5
          - ruby-2.6
          - ruby-2.7
          - ruby-3.0
          - ruby-3.1
          - ruby-3.2
          - ruby-3.3
          - ruby-head
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake compile
      - run: bundle exec rake spec

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - run: bundle exec rubocop --format progress --color
